[tool.isort]
profile = "black"
known_first_party = []
known_third_party = []
known_standard_library = []
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
line_length = 88
multi_line_output = 3
include_trailing_comma = false
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.pylint]
disable = ["C0114", "C0115", "C0116"]
