-- my_script.sql

-- Simple test queries
SELECT SYSDATE FROM DUAL
/

SELECT 
    SYS_CONTEXT('USERENV', 'SESSION_USER') AS CURRENT_USER,
    SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
    SYS_CONTEXT('USERENV', 'SERVER_HOST') AS HOST_NAME
FROM DUAL
/

-- Diagnostic SQL Script
-- This script tests database connectivity and basic operations

-- Basic Connectivity Test
SELECT SYSDATE FROM DUAL;

-- Session Information
SELECT 
    SYS_CONTEXT('USERENV', 'SESSION_USER') AS CURRENT_USER,
    SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
    SYS_CONTEXT('USERENV', 'SERVER_HOST') AS HOST_NAME
FROM DUAL;

-- Database Version
SELECT 
    BANNER as DB_VERSION,
    SYS_CONTEXT('USERENV', 'INSTANCE_NAME') as INSTANCE_NAME
FROM V$VERSION 
WHERE BANNER LIKE 'Oracle%';

-- Detailed Session Information
SELECT 
    SYS_CONTEXT('USERENV', 'SESSION_USER') AS CURRENT_USER,
    SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
    SYS_CONTEXT('USERENV', 'SERVER_HOST') AS HOST_NAME,
    SYS_CONTEXT('USERENV', 'IP_ADDRESS') AS CLIENT_IP,
    SYS_CONTEXT('USERENV', 'OS_USER') AS OS_USER,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS CURRENT_TIME
FROM DUAL;

-- Database Parameters
SELECT 
    NAME,
    VALUE,
    DESCRIPTION
FROM V$PARAMETER
WHERE NAME IN (
    'processes',
    'sessions',
    'db_block_size',
    'open_cursors'
)
ORDER BY NAME;

-- Tablespace Usage
SELECT 
    TABLESPACE_NAME,
    ROUND(USED_SPACE * 8192 / 1024 / 1024, 2) as USED_MB,
    ROUND(TABLESPACE_SIZE * 8192 / 1024 / 1024, 2) as TOTAL_MB,
    ROUND(USED_PERCENT, 2) as USED_PCT
FROM DBA_TABLESPACE_USAGE_METRICS
ORDER BY TABLESPACE_NAME;

-- Date and Timezone Settings
SELECT 
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') as SYSTEM_DATE,
    DBTIMEZONE as DB_TIMEZONE,
    SESSIONTIMEZONE as SESSION_TIMEZONE
FROM DUAL;